### ISSUE TITLE
Bridge crashes when using emoticons

### ISSUE THREAD

**Issue by muppeth** [pztrn/matrix-xmpp-bridge#2]
I noticed that using emoticons on matrix causes the bridge to crash. 
`UnicodeEncodeError: 'ascii' codec can't encode character '\U0001f490' in position 98: ordinal not in range(128)`

**Comment by muppeth** [comment]
[2016-12-12 08:26:38,249] ERROR in app: Exception on /transactions/69 [PUT]
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/flask/app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.4/dist-packages/flask/app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.4/dist-packages/flask/app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.4/dist-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/local/lib/python3.4/dist-packages/flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.4/dist-packages/flask/app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.4/dist-packages/flask_classy.py", line 200, in proxy
    response = view(**request.view_args)
  File "/srv/matrix/bridges/matrix-xmpp-bridge/appservice/appservice.py", line 71, in put
    print("Adding message to queue: {0}".format(data))
UnicodeEncodeError: 'ascii' codec can't encode character '\U0001f33c' in position 133: ordinal not in range(128)

**Comment by pztrn** [comment]
This was fixed in 847fa59ab9fa1e783daab479ecd71ec57358fd55
